
package com.devalexb.jaxws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSService", targetNamespace = "http://service.jaxws.devalexb.com/", wsdlLocation = "http://127.0.0.1:8080/WSService?wsdl")
public class WSService_Service
    extends Service
{

    private final static URL WSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSSERVICE_EXCEPTION;
    private final static QName WSSERVICE_QNAME = new QName("http://service.jaxws.devalexb.com/", "WSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/WSService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSERVICE_WSDL_LOCATION = url;
        WSSERVICE_EXCEPTION = e;
    }

    public WSService_Service() {
        super(__getWsdlLocation(), WSSERVICE_QNAME);
    }

    public WSService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSERVICE_QNAME, features);
    }

    public WSService_Service(URL wsdlLocation) {
        super(wsdlLocation, WSSERVICE_QNAME);
    }

    public WSService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSERVICE_QNAME, features);
    }

    public WSService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSService
     */
    @WebEndpoint(name = "WSService")
    public WSService getWSService() {
        return super.getPort(new QName("http://service.jaxws.devalexb.com/", "WSService"), WSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSService
     */
    @WebEndpoint(name = "WSService")
    public WSService getWSService(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jaxws.devalexb.com/", "WSService"), WSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSERVICE_EXCEPTION!= null) {
            throw WSSERVICE_EXCEPTION;
        }
        return WSSERVICE_WSDL_LOCATION;
    }

}
