
package com.devalexb.jaxws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSService", targetNamespace = "http://service.jaxws.devalexb.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertHellowWorld", targetNamespace = "http://service.jaxws.devalexb.com/", className = "com.devalexb.jaxws.service.InsertHellowWorld")
    @ResponseWrapper(localName = "insertHellowWorldResponse", targetNamespace = "http://service.jaxws.devalexb.com/", className = "com.devalexb.jaxws.service.InsertHellowWorldResponse")
    @Action(input = "http://service.jaxws.devalexb.com/WSService/insertHellowWorldRequest", output = "http://service.jaxws.devalexb.com/WSService/insertHellowWorldResponse")
    public void insertHellowWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        HelloWorld arg0);

    /**
     * 
     * @return
     *     returns com.devalexb.jaxws.service.HelloWorld
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "geHelloWorld", targetNamespace = "http://service.jaxws.devalexb.com/", className = "com.devalexb.jaxws.service.GeHelloWorld")
    @ResponseWrapper(localName = "geHelloWorldResponse", targetNamespace = "http://service.jaxws.devalexb.com/", className = "com.devalexb.jaxws.service.GeHelloWorldResponse")
    @Action(input = "http://service.jaxws.devalexb.com/WSService/geHelloWorldRequest", output = "http://service.jaxws.devalexb.com/WSService/geHelloWorldResponse")
    public HelloWorld geHelloWorld();

}
